set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)

if(DEFINED RPI_SYSROOT)
    set(RPI_SYSROOT "${RPI_SYSROOT}" CACHE STRING "Path to Raspberry Pi 5 sysroot" FORCE)
elseif(DEFINED ENV{RPI_SYSROOT})
    set(RPI_SYSROOT "$ENV{RPI_SYSROOT}" CACHE STRING "Path to Raspberry Pi 5 sysroot" FORCE)
endif()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES RPI_SYSROOT)

if(NOT RPI_SYSROOT)
    message(FATAL_ERROR "RPI_SYSROOT is not set. Please set the RPI_SYSROOT environment variable or pass -DRPI_SYSROOT=...")
endif()

set(CMAKE_SYSROOT ${RPI_SYSROOT})
set(CMAKE_FIND_ROOT_PATH ${RPI_SYSROOT})

set(CMAKE_EXE_LINKER_FLAGS "-L${RPI_SYSROOT}/usr/lib/aarch64-linux-gnu -Wl,-rpath-link=${RPI_SYSROOT}/usr/lib/aarch64-linux-gnu" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS "--sysroot=${RPI_SYSROOT} -isystem ${RPI_SYSROOT}/usr/include/aarch64-linux-gnu" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "--sysroot=${RPI_SYSROOT} -isystem ${RPI_SYSROOT}/usr/include/aarch64-linux-gnu" CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)